nelmio_api_doc:
    use_validation_groups: true
    models: { use_jms: false }
    documentation:
        info:
            title: "Ressources Relationnelles"
            description: "Documentation de l'API de gestion des ressources relationnelles (C'est de la merde, on est d'accord)"
            version: 0.1.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
