version: '3.8'

services:

  www:
    build: ./
    container_name: www_cube
    ports:
      - '8000:8000'
    dns:
      - 8.8.8.8
    volumes:
      - ./:/var/www/
    command: bash -c "composer install &&
        php bin/console doctrine:database:drop --if-exists --force &&
        php bin/console doctrine:database:create &&
        php bin/console doctrine:migrations:migrate --no-interaction &&
        php bin/console doctrine:fixtures:load --no-interaction &&
        symfony server:start
      "

  postgresql:
    image: postgres:${POSTGRES_VERSION:-14}-alpine
    container_name: postgresql_cube
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    ports:
      - 5432:5432
    expose:
      - '5432'
    volumes:
      - db-data:/var/lib/postgresql/data:rw


volumes:
  db-data: